export type Language = 'en' | 'de';

export const t = {
  en: {
    langToggle: 'DE',
    appName: 'Mietrecht Assistant',
    appTagline: 'Know your rights as a renter in Germany',

    // Nav
    navRights: 'Your Rights',
    navRentCheck: 'Rent Check',
    navLetters: 'Write a Letter',
    navGuide: 'Guide',

    // Hero
    heroTitle: 'Renter Rights in Germany',
    heroSubtitle: 'Plain English. No lawyer needed.',
    heroDesc: 'Germany has some of the strongest tenant protection laws in the world — but most renters don\'t know what they are entitled to. This tool explains your rights, checks if your rent is legal, and helps you write formal letters to your landlord.',
    heroStat1: '55%',
    heroStat1Label: 'of Germans rent their home',
    heroStat2: '€800+',
    heroStat2Label: 'average annual overpayment where Mietpreisbremse is violated',
    heroStat3: '12 months',
    heroStat3Label: 'to dispute your Nebenkosten bill',

    // Rent check
    rentCheckTitle: 'Mietpreisbremse Check',
    rentCheckDesc: 'The Mietpreisbremse (rent cap) limits new rents to a maximum of 10% above the local reference rent (ortsübliche Vergleichsmiete). Check if your rent is legal.',
    rentCheckCity: 'City',
    rentCheckSize: 'Apartment size (m²)',
    rentCheckWohnlage: 'Location quality',
    rentCheckCurrentRent: 'Your current rent (€/month)',
    rentCheckBtn: 'Check my rent',
    wohnlageEinfach: 'Simple (Einfache Wohnlage)',
    wohnlageMittel: 'Average (Mittlere Wohnlage)',
    wohnlageGut: 'Good (Gute Wohnlage)',
    rentCheckResultLegal: '✅ Your rent appears to be within the legal limit',
    rentCheckResultIllegal: '⚠️ Your rent may exceed the Mietpreisbremse limit',
    vergleichsmiete: 'Reference rent (Vergleichsmiete)',
    legalMax: 'Legal maximum (+10%)',
    yourRent: 'Your rent',
    overpaymentMonthly: 'Potential monthly overpayment',
    overpaymentAnnual: 'Potential annual overpayment',
    rentCheckDisclaimer: 'This is an estimate based on published Mietspiegel data. Some apartments are exempt (built after 2014, extensively renovated, or previously rented above this amount). Always verify with your local Mieterverein.',
    cityNotSupported: 'This city is not yet supported. We currently cover Berlin, Munich, Hamburg, Frankfurt, Cologne, Stuttgart, and Düsseldorf.',

    // Rights categories
    rightsTitle: 'Your Rights as a Tenant',
    categoryRentIncrease: 'Rent Increases',
    categoryDeposit: 'Deposit (Kaution)',
    categoryRepairs: 'Repairs & Defects',
    categoryNebenkosten: 'Utility Bills (Nebenkosten)',
    categoryEviction: 'Eviction & Notice',
    categoryMietpreisbremse: 'Mietpreisbremse',

    // Letter generator
    letterTitle: 'Generate a Formal Letter',
    letterDesc: 'Our AI generates a formal German letter on your behalf. Choose your dispute type, fill in the details, and download a ready-to-send letter.',
    letterDisputeType: 'What is the dispute about?',
    letterLandlordName: 'Landlord name',
    letterLandlordAddress: 'Landlord address',
    letterTenantName: 'Your full name',
    letterTenantAddress: 'Your address',
    letterRentalAddress: 'Rental property address',
    letterMoveIn: 'Move-in date',
    letterCurrentRent: 'Current monthly rent (€)',
    letterDetails: 'Describe your situation',
    letterDetailsHint: 'Be specific: dates, amounts, what happened, what you have already tried.',
    letterGenerateBtn: 'Generate Letter',
    letterGenerating: 'Generating your letter…',
    letterDownload: 'Download as .txt',
    letterCopy: 'Copy to clipboard',
    letterCopied: 'Copied!',
    letterDisclaimer: 'This letter is generated by AI and is for informational purposes only. Review it carefully before sending. For complex disputes, consult a Mieterverein or lawyer.',
    letterLanguageNote: 'Letter will be generated in German (formal legal language)',

    disputeTypes: {
      mietpreisbremse: 'Mietpreisbremse — Rent is too high (Rüge)',
      deposit: 'Deposit deduction dispute (Kautionsabzug)',
      repair: 'Repair request (§535 BGB)',
      nebenkosten: 'Utility bill dispute (Betriebskostenabrechnung)',
      kundigung: 'Challenge eviction notice (Kündigung)',
    },

    // Guide
    guideTitle: 'Renter\'s Guide to Germany',
    guideSubtitle: 'Essential knowledge for tenants',

    // Footer
    footerDisclaimer: 'This tool provides general legal information, not legal advice. For complex disputes, contact your local Mieterverein (tenants\' association) or a qualified Rechtsanwalt. Information is based on German law as of 2025.',
    footerMieterverein: 'Find your local Mieterverein',
    footerSources: 'Sources',

    // Common
    updatedFor: '2025',
    learnMore: 'Learn more →',
        backToHome: '← Back',
    //Letter
    letterDE: 'German Letter (send this)',
    letterEN: 'English Version (for your reference)',
    letterDownloadDE: 'Download German (.txt)',
    letterDownloadEN: 'Download English (.txt)',
    letterGeneratingBoth: 'Generating German + English letters…',
  },

  de: {
    langToggle: 'EN',
    appName: 'Mietrecht-Assistent',
    appTagline: 'Kenne deine Rechte als Mieter in Deutschland',

    navRights: 'Deine Rechte',
    navRentCheck: 'Mietcheck',
    navLetters: 'Brief schreiben',
    navGuide: 'Ratgeber',

    heroTitle: 'Mieterrechte in Deutschland',
    heroSubtitle: 'Einfach erklärt. Kein Anwalt nötig.',
    heroDesc: 'Deutschland hat eines der stärksten Mieterschutzgesetze weltweit – aber die meisten Mieter wissen nicht, was ihnen zusteht. Dieses Tool erklärt deine Rechte, prüft ob deine Miete legal ist und hilft dir, formelle Briefe an deinen Vermieter zu schreiben.',
    heroStat1: '55%',
    heroStat1Label: 'der Deutschen leben zur Miete',
    heroStat2: '800 €+',
    heroStat2Label: 'jährliche Überzahlung bei Mietpreisbremse-Verstößen',
    heroStat3: '12 Monate',
    heroStat3Label: 'Zeit zur Prüfung der Betriebskostenabrechnung',

    rentCheckTitle: 'Mietpreisbremse prüfen',
    rentCheckDesc: 'Die Mietpreisbremse begrenzt Neumieten auf maximal 10 % über der ortsüblichen Vergleichsmiete. Prüfe ob deine Miete legal ist.',
    rentCheckCity: 'Stadt',
    rentCheckSize: 'Wohnungsgröße (m²)',
    rentCheckWohnlage: 'Wohnlage',
    rentCheckCurrentRent: 'Deine aktuelle Kaltmiete (€/Monat)',
    rentCheckBtn: 'Miete prüfen',
    wohnlageEinfach: 'Einfache Wohnlage',
    wohnlageMittel: 'Mittlere Wohnlage',
    wohnlageGut: 'Gute Wohnlage',
    rentCheckResultLegal: '✅ Deine Miete liegt innerhalb der gesetzlichen Grenze',
    rentCheckResultIllegal: '⚠️ Deine Miete könnte die Mietpreisbremse überschreiten',
    vergleichsmiete: 'Ortsübliche Vergleichsmiete',
    legalMax: 'Gesetzliches Maximum (+10 %)',
    yourRent: 'Deine Miete',
    overpaymentMonthly: 'Mögliche monatliche Überzahlung',
    overpaymentAnnual: 'Mögliche jährliche Überzahlung',
    rentCheckDisclaimer: 'Dies ist eine Schätzung basierend auf veröffentlichten Mietspiegeldaten. Einige Wohnungen sind ausgenommen (Neubau nach 2014, umfassend modernisiert, oder vorher bereits höher vermietet). Bitte beim Mieterverein nachfragen.',
    cityNotSupported: 'Diese Stadt wird noch nicht unterstützt. Derzeit verfügbar: Berlin, München, Hamburg, Frankfurt, Köln, Stuttgart und Düsseldorf.',

    rightsTitle: 'Deine Mieterrechte',
    categoryRentIncrease: 'Mieterhöhungen',
    categoryDeposit: 'Kaution',
    categoryRepairs: 'Mängel & Reparaturen',
    categoryNebenkosten: 'Betriebskostenabrechnung',
    categoryEviction: 'Kündigung',
    categoryMietpreisbremse: 'Mietpreisbremse',

    letterTitle: 'Formellen Brief erstellen',
    letterDesc: 'Unsere KI erstellt einen formellen Brief in deinem Namen. Wähle dein Anliegen, fülle die Details aus und lade den Brief herunter.',
    letterDisputeType: 'Worum geht es?',
    letterLandlordName: 'Name des Vermieters',
    letterLandlordAddress: 'Adresse des Vermieters',
    letterTenantName: 'Dein vollständiger Name',
    letterTenantAddress: 'Deine Adresse',
    letterRentalAddress: 'Adresse der Mietwohnung',
    letterMoveIn: 'Einzugsdatum',
    letterCurrentRent: 'Aktuelle Kaltmiete (€)',
    letterDetails: 'Beschreibe deine Situation',
    letterDetailsHint: 'Sei konkret: Daten, Beträge, was passiert ist, was du bereits versucht hast.',
    letterGenerateBtn: 'Brief erstellen',
    letterGenerating: 'Brief wird erstellt…',
    letterDownload: 'Als .txt herunterladen',
    letterCopy: 'In Zwischenablage kopieren',
    letterCopied: 'Kopiert!',
    letterDisclaimer: 'Dieser Brief wird von einer KI erstellt und dient nur zur Information. Prüfe ihn sorgfältig bevor du ihn absendest. Für komplexe Fälle empfehlen wir den Mieterverein oder einen Rechtsanwalt.',
    letterLanguageNote: 'Der Brief wird auf Deutsch (formelle Rechtssprache) erstellt',

    disputeTypes: {
      mietpreisbremse: 'Mietpreisbremse – Miete zu hoch (Rüge)',
      deposit: 'Kautionsabzug anfechten',
      repair: 'Mängelanzeige (§ 535 BGB)',
      nebenkosten: 'Betriebskostenabrechnung anfechten',
      kundigung: 'Kündigung anfechten',
    },

    guideTitle: 'Mieter-Ratgeber Deutschland',
    guideSubtitle: 'Das Wichtigste für Mieter',

    footerDisclaimer: 'Dieses Tool bietet allgemeine Rechtsinformationen, keine Rechtsberatung. Bei komplexen Streitigkeiten wende dich an deinen lokalen Mieterverein oder einen Rechtsanwalt. Stand: 2025.',
    footerMieterverein: 'Mieterverein in deiner Nähe finden',
    footerSources: 'Quellen',

    updatedFor: '2025',
    learnMore: 'Mehr erfahren →',
      backToHome: '← Zurück',
    
    //Letter
    letterDE: 'Deutscher Brief (zum Versenden)',
    letterEN: 'Englische Version (zur Übersicht)',
    letterDownloadDE: 'Deutsch herunterladen (.txt)',
    letterDownloadEN: 'Englisch herunterladen (.txt)',
    letterGeneratingBoth: 'Deutsch + Englisch wird erstellt…',
  },
} as const;

export type T = typeof t.en;